server:
  port: 8029
  Run successful, no actions applicable

spring:

  datasource:
    dataSourceClassName: org.h2.jdbcx.JdbcDataSource
    url: jdbc:h2:mem:bd_parqueo;DB_CLOSE_DELAY=-1
    databaseName:
    serverName:
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2

  h2:
    console:
      enabled: true
